[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.13"
sea-orm = { version = "0.9.1", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
